### PR TITLE
Player DSF, DFF file incorrect speed  . Background white noise

### PR DESCRIPTION
**Pull request by hicaoc**
ALSA DSD_U32_BE correction mode , the player DSF, DFF file incorrect speed : 4x speed playback . Background white noise

### CODE REVIEW

**Comment by MaxKellermann** [comment]
I don't understand your commits, because not a single one contains a useful description.

**Comment by hicaoc** [comment]
I'm sorry , cancel it , this is just a correction of an error DSD playback : Playback speed is too fast and the background noise.
Wait until you fix this bug

**Comment by MaxKellermann** [comment]
I don't understand. What bug is this? There is no bug report on the MPD bug tracker. Your commits are undocumented, the description just says "Update", but update what, how and why? "Update ..." is a bad description.

**Comment by hicaoc** [comment]
@MaxKellermann  
Bug report ：
https://bugs.musicpd.org/view.php?id=4514

**Comment by xxxbugxxxx** [comment]
Same issue here

**Comment by xxxbugxxxx** [comment]
When playing 
Status: Running
    Interface = 1
    Altset = 3
    Packet Size = 392
    Momentary freq = 352844 Hz (0x2c.1b00)
    Feedback Format = 16.16
  Interface 1
    Altset 1
    Format: S32_LE
    Channels: 2
    Endpoint: 1 OUT (ASYNC)
    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
  Interface 1
    Altset 2
    Format: S16_LE
    Channels: 2
    Endpoint: 1 OUT (ASYNC)
    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
  Interface 1
    Altset 3
    Format: SPECIAL DSD_U32_BE
    Channels: 2
    Endpoint: 1 OUT (ASYNC)
    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
    Data packet interval: 125 us
When playing a DSD64 file

**Comment by hicaoc** [comment]
try :
https://github.com/MaxKellermann/MPD

**Comment by xxxbugxxxx** [comment]
will try now. Thanks

**Comment by xxxbugxxxx** [comment]
worked like a charm, Thank you very much!

Test environment, Volumio 1.55, kernel updated to 4.4.6-v7+

Custard X-20U DAC. running Hicaoc's repo.

**Comment by hicaoc** [comment]
Thanks for the feedback

**Comment by xxxbugxxxx** [comment]
updated musicpd's bug tracker also. Been waiting for this ultimate mix of SACD ISO and native DSD support for a long time. i am not a coder myself. just barely understand C/C++

**Comment by MaxKellermann** [comment]
@hicaoc you closed this pull request, after you refused to document your code. I would welcome your contributions, but you refused to do so. What's this continued discussion about, then?

**Pull request closed without merging**
